export type ResourceLink = { title: string; href: string; description?: string; kind?: string; subLinks?: { label: string; href: string }[] }
export type ResourceGroup = { id: string; title: string; description: string; icon: string; links: ResourceLink[] }

export const RESOURCE_GROUPS: ResourceGroup[] = [
  {
    id: 'docs',
    title: 'References / Docs',
    description: 'Language docs, file formats, protocol notes, and archival references.',
    icon: 'docs',
    links: [
      { title: 'Wiki', href: 'https://wiki.gscript.dev/Creation/Dev/GScript', description: 'Creation wiki mirror for scripting docs.' },
      { title: 'File Formats', href: '/?formats', description: 'NW, GMAP, Zelda, Graal, and GANI format notes.' },
      { title: 'GScript Documentation', href: '/?docs', description: 'Searchable indexed scripting reference.' },
      { title: "Ruan's GS2 Docs", href: '/ruandoc', description: 'Alternate GS2 documentation archive.' },
      { title: 'RC Protocol', href: 'https://morenoland.github.io/GScript.RCDocs/', description: 'Remote Control protocol documentation.' },
      { title: 'Client Protocol', href: 'https://reborn-protocol-docs.readthedocs.io/en/latest/', description: 'Client protocol docs.' },
      { title: 'Server Statistics', href: 'https://stats.gscript.dev/', description: 'Server list and activity stats.' },
      { title: 'OGCC Archive', href: 'https://forums.gscript.dev/', description: 'Forum archive.' },
    ],
  },
  {
    id: 'tools',
    title: 'Web Tools',
    description: 'Browser tools for editing, converting, testing, and sharing.',
    icon: 'tools',
    links: [
      { title: 'Graal Suite', href: 'https://suite.gscript.dev', description: 'Editor suite.' },
      { title: 'Gmap Generator', href: 'https://gmap.gscript.dev/', description: 'Generate GMAPs in browser.' },
      { title: "Mem's Mobile Editor", href: 'https://sleepyeepy.cloud/tiles-editor/', description: 'Mobile-friendly level editor.' },
      { title: "Pluto's Level Editor", href: 'https://geditor.net/', description: 'Web level editor.' },
      { title: 'GS2 Emulator', href: 'https://gs2.gscript.dev/', description: 'GS2 runtime testbed.' },
      { title: 'Beautifier', href: '/?beautify', description: 'Format GS2 source.' },
      { title: 'Graphics Previewer', href: 'https://fungsiyan.github.io/previewer/', description: 'Preview graphics.' },
      { title: 'setshape2 / setimgpart', href: 'https://setshape.gscript.dev', description: 'Graphics helper.' },
    ],
  },
  {
    id: 'assets',
    title: 'Assets / Links',
    description: 'Templates, image packs, indexing guides, and external resource lists.',
    icon: 'assets',
    links: [
      { title: 'Player Templates', href: '/PlayerSubmissionTemplates.zip', description: 'Player template download.' },
      { title: 'player-param1 Templates', href: 'https://github.com/fungsiyan/assets/tree/main/templates/player-param1', description: 'Template source.' },
      { title: 'Coco Templates', href: '/CocoTemplates.zip', description: 'Coco template pack.' },
      { title: 'fungsiyan Assets', href: 'https://github.com/fungsiyan/assets', description: 'Asset repository.' },
      { title: 'GScript LSP Data', href: 'https://api.gscript.dev/', description: 'Language-server data.' },
      { title: 'fungsiyan Resource List', href: 'https://fungsiyan.github.io/index/', description: 'Extra resources.' },
      { title: 'GraalServer', href: '/graalserver', description: 'Preagonal server links.', subLinks: [{ label: 'Account Creation', href: 'https://graalserver.com/accountcreator.php' }, { label: 'Settings', href: 'https://www.graalserver.com/user/settings' }] },
      { title: 'Graphics Indexing Guides (Gimp / PS)', href: '/?indexing', description: 'Graphics indexing guide.' },
    ],
  },
  {
    id: 'downloads',
    title: 'Downloads / Sources',
    description: 'Clients, editors, extensions, utilities, and source repositories.',
    icon: 'downloads',
    links: [
      { title: 'Graal Suite', href: 'https://github.com/MorenoLand/GScript.GraalSuite', description: 'Suite source and releases.', kind: 'Win / Linux / Mac' },
      { title: 'RC3', href: '/rc3_win_dark.zip', description: 'RC3 builds.', kind: 'Win / Mac' },
      { title: 'RC2', href: '/rc2_dark_win.zip', description: 'RC2 builds.', kind: 'Win / Linux' },
      { title: 'Level/Gani Editor (39ster)', href: 'https://github.com/lukegrahamSydney/TilesEditor', description: 'Tiles/Gani editor source and builds.', kind: 'Win / Linux' },
      { title: 'Gonstruct', href: 'https://github.com/fry/graal-gonstruct', description: 'Level editor source and builds.', kind: 'Win / Linux' },
      { title: 'RC Patcher', href: 'https://github.com/MorenoLand/Preagonal.RCPatcher', description: 'RC utility.' },
      { title: '2FA Fix', href: 'https://github.com/Denveous/graal-2fa-fix', description: 'Account utility.' },
      { title: 'GCLib', href: 'https://github.com/MorenoLand/GScript.GCLib', description: 'Library source.' },
      { title: 'GRClib', href: 'https://github.com/MorenoLand/GScript.GRClib', description: 'RC library source.' },
      { title: 'Sublime LSP', href: 'https://github.com/MorenoLand/GScript.SublimeLSP', description: 'Sublime language server package.' },
      { title: 'SublimeRC', href: 'https://github.com/MorenoLand/GScript.SublimeRC', description: 'Sublime RC package.' },
      { title: 'Sublime Syntax', href: 'https://github.com/MorenoLand/GScript.SublimeHightlighting', description: 'Sublime syntax highlighting.' },
      { title: 'VSCode LSP', href: 'https://marketplace.visualstudio.com/items?itemName=ruanfernandes.graalscript-lsp', description: 'VSCode language server.' },
      { title: 'GRC VSCode', href: 'https://github.com/xtjoeytx/grc-vscode-ext', description: 'VSCode RC extension.' },
      { title: 'HxD Plugin', href: 'https://github.com/Preagonal/HxDGraal', description: 'HxD helper plugin.' },
      { title: 'VSIX Syntax', href: '/graal-language-0.0.1.vsix', description: 'VSCode syntax package.' },
    ],
  },
  {
    id: 'videos',
    title: 'Videos',
    description: 'Tutorials and channel archives.',
    icon: 'videos',
    links: [
      { title: 'GS2 Tutorial', href: 'https://www.youtube.com/playlist?list=PLGCNVthRlw5EHakguzfJe4E2N9HrMhCb4' },
      { title: 'GS2 Intro', href: 'https://youtu.be/nOA0iOOaeQA' },
      { title: 'GS2 Basics', href: 'https://www.youtube.com/playlist?list=PLj7V7gCaCF2u-MrVyTn1c3ZN01BHKGq2m' },
      { title: 'Graal Developers', href: 'https://www.youtube.com/@graalonlinedevelopers1547/videos' },
      { title: 'iMagic', href: 'https://www.youtube.com/@iMagicIAm/videos' },
      { title: 'BiTzSAM', href: 'https://www.youtube.com/@D34dlyI3rute/videos' },
      { title: 'Syahrul', href: 'https://www.youtube.com/@syahrulzahwan/videos' },
      { title: 'Gani Intro', href: 'https://www.youtube.com/playlist?list=PLtDohBs99GZeZgYIX97nFtj_ik4zbM845' },
      { title: 'Gani Frames', href: 'https://www.youtube.com/watch?v=MdUGHXZAAMY' },
      { title: 'Gani Action', href: 'https://www.youtube.com/watch?v=T5xOwGuymBw' },
      { title: 'Gani Melee', href: 'https://www.youtube.com/@swiggerswogger8818' },
      { title: 'Gani Gun', href: 'https://www.youtube.com/watch?v=6vrXDhQ-d5k' },
      { title: 'GIMP Drawing', href: 'https://www.youtube.com/watch?v=LlXa5FyrIb8' },
      { title: 'GIMP Recoloring', href: 'https://www.youtube.com/watch?v=9Ku6R8tzEj0' },
      { title: 'GIMP GIFs', href: 'https://www.youtube.com/watch?v=2QShpdhsnLE' },
      { title: 'Pixel Studio', href: 'https://www.youtube.com/watch?v=ry8q8srzpIc' },
      { title: 'Coco', href: 'https://www.youtube.com/playlist?list=PLkJnsgy7P_5pxaHAYDXYIAPMwmrRCjVn8' },
      { title: 'Leah', href: 'https://www.youtube.com/@LeahLikesToDraw/videos' },
      { title: 'Graal Modders', href: 'https://www.youtube.com/@TheGraalModders' },
      { title: 'Localization RU', href: 'https://www.youtube.com/watch?v=qAn9yHqbAsY' },
      { title: 'Kuroneko', href: 'https://www.youtube.com/@cky2013/videos' },
      { title: 'Robg', href: 'https://www.youtube.com/@RobG-videos/videos' },
      { title: 'Classic Graal', href: 'https://www.youtube.com/@classicgraal' },
      { title: 'NYN', href: 'https://www.youtube.com/@newyorkernick/videos' },
    ],
  },
]
